# Local Development Deployment (without code mounting)
# docker compose -f dockerfiles/w3_docker_compose_local.yml -p webmud3local up -d
services:
  web:
    image: myonara/webmud3:latest
    environment:
      NODE_ENV: 'production'
      HOST: '0.0.0.0'
      PORT: 5000
      TELNET_HOST: 'host.docker.internal'
      TELNET_PORT: 4000
      TELNET_TLS: 'false'
      SOCKET_ROOT: '/socket.io'
      SOCKET_TIMEOUT: 900000
      LOG_LEVEL: 'debug'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 2
        window: 3600s
    ports:
      - "2018:5000"
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
