# UNItopia Test Deployment (tagged image)
# docker compose -f dockerfiles/w3_docker_compose_test_neu.yml -p webmud3testneu up -d
services:
  web:
    image: myonara/webmud3:unitopiatest
    environment:
      NODE_ENV: 'production'
      HOST: '0.0.0.0'
      PORT: 5000
      SOCKET_ROOT: '/mysocket-test.io'
      SOCKET_TIMEOUT: 900000
      MUD_CONFIG_PATH: '/run/mud_config_unitopia_test.json'
      CORS_ALLOWED_ORIGINS: 'https://www.unitopia.de'
      LOG_LEVEL: 'debug'
    volumes:
      - "/UNItopia/ftpwww/webmud3/run:/run"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      labels:
        com.docker.lb.hosts: www.unitopia.de
        com.docker.lb.network: webnet
        com.docker.lb.port: 2019
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 2
        window: 3600s
    ports:
      - "2019:5000"
    networks:
      - webnet
networks:
  webnet:
    attachable: true
