# UNItopia Production Deployment
# docker compose -f dockerfiles/w3_docker_compose.yml -p webmud3 up -d
services:
  web:
    image: myonara/webmud3:latest
    environment:
      NODE_ENV: 'production'
      HOST: '0.0.0.0'
      PORT: 5000
      SOCKET_ROOT: '/mysocket.io'
      SOCKET_TIMEOUT: 900000
      MUD_CONFIG_PATH: '/run/mud_config_unitopia.json'
      CORS_ALLOWED_ORIGINS: 'https://www.unitopia.de'
      LOG_LEVEL: 'info'
    volumes:
      - "/UNItopia/ftpwww/webmud3/run:/run"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      labels:
        com.docker.lb.hosts: www.unitopia.de
        com.docker.lb.network: webnet
        com.docker.lb.port: 2018
      restart_policy:
        condition: on-failure
    ports:
      - "2018:5000"
    networks:
      - webnet
networks:
  webnet:
    attachable: true
