# Seifenblase Production Deployment
# docker compose -f dockerfiles/w3_docker_compose_sb.yml -p webmud3sb up -d
services:
  web:
    image: myonara/webmud3:latest
    environment:
      NODE_ENV: 'production'
      HOST: '0.0.0.0'
      PORT: 5000
      SOCKET_ROOT: '/sbsocket.io'
      SOCKET_TIMEOUT: 900000
      MUD_CONFIG_PATH: '/run/mud_config_seifenblase.json'
      CORS_ALLOWED_ORIGINS: 'https://seife.mud.de,https://seifenblase.de,https://www.seifenblase.de,https://mud.seifenblase.de,https://seifenblase.mud.de'
      LOG_LEVEL: 'info'
    volumes:
      - "/UNItopia/ftpwww/webmud3/run:/run"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      labels:
        com.docker.lb.hosts: seife.mud.de
        com.docker.lb.network: webnetsb
        com.docker.lb.port: 2020
      restart_policy:
        condition: on-failure
    ports:
      - "2020:5000"
    networks:
      - webnetsb
networks:
  webnetsb:
    attachable: true
