version: "3.7"
services:
  web:
    image: myonara/webmud3:latest
    environment: 
      NODE_ENV: 'production'
      SECRET_CONFIG: '/run/webmud3.json'
      MUD_CONFIG: '/run/mud_config_unitopia.json'
      WEBMUD3_DISTRIBUTION_TYPE: 'unitopia-prod'
    volumes:
      - "/mnt/run:/run"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      labels:
        com.docker.lb.hosts: www.unitopia.de
        com.docker.lb.network: webnet
        com.docker.lb.port: 5000
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    networks:
      - webnet
networks:
  webnet:
    #driver: overlay
    attachable: true
