services: 
  # docker compose -f dockerfiles/wm3_local_dev.yml -p webmud3dev up -d
  web:
    image: myonara/webmud3:wm3local
    environment: 
      ENVIRONMENT: 'development'
      NODE_ENV: 'development'
      NAME: 'webmud3myonara'
      HOST: '0.0.0.0'
      PORT: 5000
      TELNET_HOST: 'unitopia.de'
      TELNET_PORT: 9988
      TELNET_TLS: 'true'
      SOCKET_ROOT: '/mysocket-local.io'
      SOCKET_TIMEOUT: 900000
      LOG_LEVEL: 'debug'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      labels:
        com.docker.lb.hosts: www.unitopia.de
        com.docker.lb.network: webnet
        com.docker.lb.port: 5000
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 2 
        window: 3600s
    ports:
      - "5000:5000"
    networks:
      - webnet
networks:
  webnet:
    driver: overlay
